language: node_js

node_js:
  - "8"

git:
  depth: 2

before_install:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"

script:
  - git checkout $BRANCH
  - node build.js

deploy:
  provider: script
  script: .travis-ci/deploy.sh
  skip_cleanup: true
  on:
    branch: master
